version: "3.8"

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /media/diskext1/docker/mqtt/mosquitto/config:/mosquitto/config
      - /media/diskext1/docker/mqtt/mosquitto/data:/mosquitto/data
      - /media/diskext1/docker/mqtt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iotbeesnet

  influx:
    container_name: influx
    image: influxdb
    restart: always
    volumes:
      - /media/diskext1/docker/influx:/var/lib/influxdb
      - /media/diskext1/docker/influx/influxdb.conf:/opt/bitnami/influxdb/etc/influxdb.conf:ro
    ports:
      - 8086:8086
    networks:
      - iotbeesnet
    environment:
      - INFLUXDB_DB=iotbeesdb1
      - INFLUXDB_ADMIN_USER=userinflux1
      - INFLUXDB_ADMIN_PASSWORD=password

  grafana:
    container_name: grafana
    image: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - iotbeesnet
    volumes:
      - /media/diskext1/docker/grafana:/var/lib/grafana

networks:
  iotbeesnet:
